name: publish

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Preparation - Setup Python and Conda
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - uses: conda-incubator/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: '3.8'

    - name: Preparation - Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine grayskull
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build and publish to pypi (test)
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload --repository testpypi --verbose dist/*

    - name: Publish to pypi (production)
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        twine upload --verbose dist/*

    - name: Build and publish to conda (production)
      env:
        CONDA_TOKEN: ${{ secrets.CONDA_TOKEN }}
      run: |
        grayskull pypi castoredc_api
        conda-build castoredc_api
        conda convert --platform all ~/opt/anaconda3/conda-bld/osx-64/castoredc_api*.bz2 -o ~/opt/anaconda3/conda-bld/
        anaconda -t CONDA_TOKEN upload --skip-existing ~/opt/anaconda3/conda-bld/*/castorapi*.bz2